[versions]
compose-bom = "2025.06.00"

compileSdk = "36"
minSdk = "24"
targetSdk = "36"

detekt = "1.23.8"
ktlint = "12.3.0"
moduleGraphAssertion = "2.8.0"
gradleDoctor = "0.11.0"
dependencyAnalysis = "2.17.0"
jacocoAggregation = "2.4.4"
composeRules = "0.4.22"

agp = "8.10.1"
androidTools = "31.10.1"
androidDesugarJdkLibs = "2.1.5"

kotlin = "2.1.21"
coroutines = "1.10.2"
ksp = "2.1.21-2.0.1"
kotlin-serialization-plugin = "2.1.21"
kotlin-serialization-json = "1.8.1"

dagger = "2.56.2"
androidx-hilt = "1.2.0"

core-ktx = "1.16.0"
appcompat = "1.7.1"
archCore = "2.2.0"
androidxTestCore = "1.6.1"
androidx-junit = "1.2.1"
androidxTestRunner = "1.6.2"
androidxTestRules = "1.6.1"

material = "1.12.0"
mockk = "1.14.2"
navigation = "2.9.0"
activity-compose = "1.10.1"
lifecycle = "2.9.1"
constraintLayout = "1.1.1"
paging = "3.3.6"

gson = "2.12.1"
robolectric = "4.14.1"
timber = "5.0.1"
coil = "2.7.0"
retrofit = "2.11.0"
okhttp = "4.12.0"
moshi = "1.15.2"
vanpra = "0.7.0"
markwon = "4.6.2"
junit4 = "4.13.2"
turbine = "1.2.0"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
jetbrainsKotlinJvm = "2.1.21"

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayout" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "archCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }

android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
markwon-image-coil = { module = "io.noties.markwon:image-coil", version.ref = "markwon" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
material = { module = "com.google.android.material:material", version.ref = "material" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
vanpra-color = { module = "io.github.vanpra.compose-material-dialogs:color", version.ref = "vanpra" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "dagger" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

composeRules-ktlint = { module = "io.nlopez.compose.rules:ktlint", version.ref = "composeRules" }
composeRules-detekt = { module = "io.nlopez.compose.rules:detekt", version.ref = "composeRules" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization-plugin" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
moduleGraphAssertion = { id = "com.jraska.module.graph.assertion", version.ref = "moduleGraphAssertion" }
gradleDoctor = { id = "com.osacky.doctor", version.ref = "gradleDoctor" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
jacocoAggregationCoverage = { id = "io.github.gmazzo.test.aggregation.coverage", version.ref = "jacocoAggregation" }
jacocoAggregationResults = { id = "io.github.gmazzo.test.aggregation.results", version.ref = "jacocoAggregation" }

# Plugins definded in the included build-logic
taigamobile-android-application = { id = "taigamobile.android.application" }
taigamobile-android-hilt = { id = "taigamobile.android.hilt" }
taigamobile-kotlin-hilt = { id = "taigamobile.kotlin.hilt" }
taigamobile-android-library = { id = "taigamobile.android.library" }
taigamobile-android-library-compose = { id = "taigamobile.android.library.compose" }
taigamobile-kotlin-serialization = { id = "taigamobile.kotlin.serialization" }
taigamobile-kotlin-library = { id = "taigamobile.kotlin.library" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
